### ISSUE TITLE
new website: follow up issues

### ISSUE THREAD

**Issue by deerboy** [deerboy/demodemodemo#2]
- [ ] whitespace on right of header bar for screens < 360px  (https://github.com/gr2m/octokit-rest-documentation/issues/42)
- [ ] After click on menu, target heading is hidden behind header bar (https://github.com/gr2m/octokit-rest-documentation/issues/40)
- [ ] Update URL when scrolling between sections (https://github.com/gr2m/octokit-rest-documentation/issues/5)
- [ ] Make 3 column design (https://github.com/gr2m/octokit-rest-documentation/issues/20)
